### ISSUE TITLE
zio-logging 2.1.11 does not work with zio 2.0.11

### ISSUE THREAD

**Issue by limpid-kzonix** [zio/zio-logging#706]
```
timestamp=2023-04-07T21:34:21.250661320Z level=ERROR thread=#zio-fiber-0 message="" cause="Exception in thread "zio-fiber-1,0" java.lang.NoSuchMethodError: 'zio.Config zio.Config.nested(scala.Function0)'
	at zio.logging.ConsoleLoggerConfig$.<clinit>(ConsoleLoggerConfig.scala:27)
	at io.kzonix.meeter.MeeterApp$.$init$$$anonfun$1(MeeterApp.scala:16)
	at zio.ZLayer$ZLayerProvideSomeOps$.$greater$greater$greater$extension$$anonfun$2(ZLayer.scala:1843)
	at zio.ZLayer.scope$$anonfun$6$$anonfun$1(ZLayer.scala:406)
	at zio.ZLayer$MemoMap$$anon$41.$anonfun$4$$anonfun$2$$anonfun$1$$anonfun$1$$anonfun$1(ZLayer.scala:1749)"
```

The example to reproduce
```
import zio.*
import zio.http.*
import zio.logging.*
import zio.metrics.jvm.DefaultJvmMetrics


object App extends ZIOAppDefault {
  
  override val bootstrap: ZLayer[Any, Any, Any] =
    Runtime.removeDefaultLoggers
      >>> consoleJsonLogger(ConsoleLoggerConfig.default)

  override def run: ZIO[Any, Any, Any] =
    (for {
      _ <- ZIO.logInfo("Hello ZIO")
    } yield ()).provide(
      // ZLayer.Debug.tree,
    )

}
```
Project deps
```
      "dev.zio"                    %% "zio"                    % "2.0.11",
      "dev.zio"                    %% "zio-logging"            % "2.1.11",
```

**Comment by limpid-kzonix** [comment]
https://github.com/zio/zio/pull/7965

**Comment by justcoon** [comment]
@limpid-kzonix thank your for report

working on new release

**Comment by limpid-kzonix** [comment]
🟢 tested zio-logging v2.1.12 with zio v2.0.11
